// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"cinema/internal/lib/jwt"
	"cinema/internal/sso/domain"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionStorage creates a new instance of MockSessionStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStorage {
	mock := &MockSessionStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionStorage is an autogenerated mock type for the SessionStorage type
type MockSessionStorage struct {
	mock.Mock
}

type MockSessionStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStorage) EXPECT() *MockSessionStorage_Expecter {
	return &MockSessionStorage_Expecter{mock: &_m.Mock}
}

// DeleteAllSessions provides a mock function for the type MockSessionStorage
func (_mock *MockSessionStorage) DeleteAllSessions(ctx context.Context, userId string) error {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStorage_DeleteAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllSessions'
type MockSessionStorage_DeleteAllSessions_Call struct {
	*mock.Call
}

// DeleteAllSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockSessionStorage_Expecter) DeleteAllSessions(ctx interface{}, userId interface{}) *MockSessionStorage_DeleteAllSessions_Call {
	return &MockSessionStorage_DeleteAllSessions_Call{Call: _e.mock.On("DeleteAllSessions", ctx, userId)}
}

func (_c *MockSessionStorage_DeleteAllSessions_Call) Run(run func(ctx context.Context, userId string)) *MockSessionStorage_DeleteAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionStorage_DeleteAllSessions_Call) Return(err error) *MockSessionStorage_DeleteAllSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStorage_DeleteAllSessions_Call) RunAndReturn(run func(ctx context.Context, userId string) error) *MockSessionStorage_DeleteAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockSessionStorage
func (_mock *MockSessionStorage) DeleteSession(ctx context.Context, userId string, token string) error {
	ret := _mock.Called(ctx, userId, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userId, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStorage_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionStorage_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - token string
func (_e *MockSessionStorage_Expecter) DeleteSession(ctx interface{}, userId interface{}, token interface{}) *MockSessionStorage_DeleteSession_Call {
	return &MockSessionStorage_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, userId, token)}
}

func (_c *MockSessionStorage_DeleteSession_Call) Run(run func(ctx context.Context, userId string, token string)) *MockSessionStorage_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionStorage_DeleteSession_Call) Return(err error) *MockSessionStorage_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStorage_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, userId string, token string) error) *MockSessionStorage_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// IsSessionExists provides a mock function for the type MockSessionStorage
func (_mock *MockSessionStorage) IsSessionExists(ctx context.Context, userId string, token string) (bool, error) {
	ret := _mock.Called(ctx, userId, token)

	if len(ret) == 0 {
		panic("no return value specified for IsSessionExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userId, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userId, token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userId, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionStorage_IsSessionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSessionExists'
type MockSessionStorage_IsSessionExists_Call struct {
	*mock.Call
}

// IsSessionExists is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - token string
func (_e *MockSessionStorage_Expecter) IsSessionExists(ctx interface{}, userId interface{}, token interface{}) *MockSessionStorage_IsSessionExists_Call {
	return &MockSessionStorage_IsSessionExists_Call{Call: _e.mock.On("IsSessionExists", ctx, userId, token)}
}

func (_c *MockSessionStorage_IsSessionExists_Call) Run(run func(ctx context.Context, userId string, token string)) *MockSessionStorage_IsSessionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionStorage_IsSessionExists_Call) Return(b bool, err error) *MockSessionStorage_IsSessionExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSessionStorage_IsSessionExists_Call) RunAndReturn(run func(ctx context.Context, userId string, token string) (bool, error)) *MockSessionStorage_IsSessionExists_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSession provides a mock function for the type MockSessionStorage
func (_mock *MockSessionStorage) SaveSession(ctx context.Context, userId string, token string, ttl time.Duration) error {
	ret := _mock.Called(ctx, userId, token, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SaveSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, userId, token, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStorage_SaveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSession'
type MockSessionStorage_SaveSession_Call struct {
	*mock.Call
}

// SaveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - token string
//   - ttl time.Duration
func (_e *MockSessionStorage_Expecter) SaveSession(ctx interface{}, userId interface{}, token interface{}, ttl interface{}) *MockSessionStorage_SaveSession_Call {
	return &MockSessionStorage_SaveSession_Call{Call: _e.mock.On("SaveSession", ctx, userId, token, ttl)}
}

func (_c *MockSessionStorage_SaveSession_Call) Run(run func(ctx context.Context, userId string, token string, ttl time.Duration)) *MockSessionStorage_SaveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionStorage_SaveSession_Call) Return(err error) *MockSessionStorage_SaveSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStorage_SaveSession_Call) RunAndReturn(run func(ctx context.Context, userId string, token string, ttl time.Duration) error) *MockSessionStorage_SaveSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResetTokenStorage creates a new instance of MockResetTokenStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResetTokenStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResetTokenStorage {
	mock := &MockResetTokenStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResetTokenStorage is an autogenerated mock type for the ResetTokenStorage type
type MockResetTokenStorage struct {
	mock.Mock
}

type MockResetTokenStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResetTokenStorage) EXPECT() *MockResetTokenStorage_Expecter {
	return &MockResetTokenStorage_Expecter{mock: &_m.Mock}
}

// DeleteResetToken provides a mock function for the type MockResetTokenStorage
func (_mock *MockResetTokenStorage) DeleteResetToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResetToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResetTokenStorage_DeleteResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResetToken'
type MockResetTokenStorage_DeleteResetToken_Call struct {
	*mock.Call
}

// DeleteResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockResetTokenStorage_Expecter) DeleteResetToken(ctx interface{}, token interface{}) *MockResetTokenStorage_DeleteResetToken_Call {
	return &MockResetTokenStorage_DeleteResetToken_Call{Call: _e.mock.On("DeleteResetToken", ctx, token)}
}

func (_c *MockResetTokenStorage_DeleteResetToken_Call) Run(run func(ctx context.Context, token string)) *MockResetTokenStorage_DeleteResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResetTokenStorage_DeleteResetToken_Call) Return(err error) *MockResetTokenStorage_DeleteResetToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResetTokenStorage_DeleteResetToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockResetTokenStorage_DeleteResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserIdByResetToken provides a mock function for the type MockResetTokenStorage
func (_mock *MockResetTokenStorage) GetUserIdByResetToken(ctx context.Context, token string) (string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIdByResetToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResetTokenStorage_GetUserIdByResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserIdByResetToken'
type MockResetTokenStorage_GetUserIdByResetToken_Call struct {
	*mock.Call
}

// GetUserIdByResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockResetTokenStorage_Expecter) GetUserIdByResetToken(ctx interface{}, token interface{}) *MockResetTokenStorage_GetUserIdByResetToken_Call {
	return &MockResetTokenStorage_GetUserIdByResetToken_Call{Call: _e.mock.On("GetUserIdByResetToken", ctx, token)}
}

func (_c *MockResetTokenStorage_GetUserIdByResetToken_Call) Run(run func(ctx context.Context, token string)) *MockResetTokenStorage_GetUserIdByResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResetTokenStorage_GetUserIdByResetToken_Call) Return(s string, err error) *MockResetTokenStorage_GetUserIdByResetToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockResetTokenStorage_GetUserIdByResetToken_Call) RunAndReturn(run func(ctx context.Context, token string) (string, error)) *MockResetTokenStorage_GetUserIdByResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveResetToken provides a mock function for the type MockResetTokenStorage
func (_mock *MockResetTokenStorage) SaveResetToken(ctx context.Context, userId string, token string, ttl time.Duration) error {
	ret := _mock.Called(ctx, userId, token, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SaveResetToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, userId, token, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResetTokenStorage_SaveResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveResetToken'
type MockResetTokenStorage_SaveResetToken_Call struct {
	*mock.Call
}

// SaveResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - token string
//   - ttl time.Duration
func (_e *MockResetTokenStorage_Expecter) SaveResetToken(ctx interface{}, userId interface{}, token interface{}, ttl interface{}) *MockResetTokenStorage_SaveResetToken_Call {
	return &MockResetTokenStorage_SaveResetToken_Call{Call: _e.mock.On("SaveResetToken", ctx, userId, token, ttl)}
}

func (_c *MockResetTokenStorage_SaveResetToken_Call) Run(run func(ctx context.Context, userId string, token string, ttl time.Duration)) *MockResetTokenStorage_SaveResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResetTokenStorage_SaveResetToken_Call) Return(err error) *MockResetTokenStorage_SaveResetToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResetTokenStorage_SaveResetToken_Call) RunAndReturn(run func(ctx context.Context, userId string, token string, ttl time.Duration) error) *MockResetTokenStorage_SaveResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// FindByEmail provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) FindByEmail(ctx context.Context, email string) (domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserProvider_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserProvider_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserProvider_FindByEmail_Call {
	return &MockUserProvider_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserProvider_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserProvider_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_FindByEmail_Call) Return(user domain.User, err error) *MockUserProvider_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (domain.User, error)) *MockUserProvider_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) FindById(ctx context.Context, id string) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockUserProvider_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserProvider_Expecter) FindById(ctx interface{}, id interface{}) *MockUserProvider_FindById_Call {
	return &MockUserProvider_FindById_Call{Call: _e.mock.On("FindById", ctx, id)}
}

func (_c *MockUserProvider_FindById_Call) Run(run func(ctx context.Context, id string)) *MockUserProvider_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_FindById_Call) Return(user domain.User, err error) *MockUserProvider_FindById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_FindById_Call) RunAndReturn(run func(ctx context.Context, id string) (domain.User, error)) *MockUserProvider_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) SaveUser(ctx context.Context, email string, passHash []byte) (string, error) {
	ret := _mock.Called(ctx, email, passHash)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return returnFunc(ctx, email, passHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = returnFunc(ctx, email, passHash)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, email, passHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUserProvider_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passHash []byte
func (_e *MockUserProvider_Expecter) SaveUser(ctx interface{}, email interface{}, passHash interface{}) *MockUserProvider_SaveUser_Call {
	return &MockUserProvider_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, email, passHash)}
}

func (_c *MockUserProvider_SaveUser_Call) Run(run func(ctx context.Context, email string, passHash []byte)) *MockUserProvider_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserProvider_SaveUser_Call) Return(id string, err error) *MockUserProvider_SaveUser_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *MockUserProvider_SaveUser_Call) RunAndReturn(run func(ctx context.Context, email string, passHash []byte) (string, error)) *MockUserProvider_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserEmail provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) UpdateUserEmail(ctx context.Context, userId string, email string) error {
	ret := _mock.Called(ctx, userId, email)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userId, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserProvider_UpdateUserEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserEmail'
type MockUserProvider_UpdateUserEmail_Call struct {
	*mock.Call
}

// UpdateUserEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - email string
func (_e *MockUserProvider_Expecter) UpdateUserEmail(ctx interface{}, userId interface{}, email interface{}) *MockUserProvider_UpdateUserEmail_Call {
	return &MockUserProvider_UpdateUserEmail_Call{Call: _e.mock.On("UpdateUserEmail", ctx, userId, email)}
}

func (_c *MockUserProvider_UpdateUserEmail_Call) Run(run func(ctx context.Context, userId string, email string)) *MockUserProvider_UpdateUserEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserProvider_UpdateUserEmail_Call) Return(err error) *MockUserProvider_UpdateUserEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserProvider_UpdateUserEmail_Call) RunAndReturn(run func(ctx context.Context, userId string, email string) error) *MockUserProvider_UpdateUserEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) UpdateUserPassword(ctx context.Context, userId string, passHash []byte) error {
	ret := _mock.Called(ctx, userId, passHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, userId, passHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserProvider_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type MockUserProvider_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - passHash []byte
func (_e *MockUserProvider_Expecter) UpdateUserPassword(ctx interface{}, userId interface{}, passHash interface{}) *MockUserProvider_UpdateUserPassword_Call {
	return &MockUserProvider_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", ctx, userId, passHash)}
}

func (_c *MockUserProvider_UpdateUserPassword_Call) Run(run func(ctx context.Context, userId string, passHash []byte)) *MockUserProvider_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserProvider_UpdateUserPassword_Call) Return(err error) *MockUserProvider_UpdateUserPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserProvider_UpdateUserPassword_Call) RunAndReturn(run func(ctx context.Context, userId string, passHash []byte) error) *MockUserProvider_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserRole provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) UpdateUserRole(ctx context.Context, userId string, role string) error {
	ret := _mock.Called(ctx, userId, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userId, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserProvider_UpdateUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserRole'
type MockUserProvider_UpdateUserRole_Call struct {
	*mock.Call
}

// UpdateUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - role string
func (_e *MockUserProvider_Expecter) UpdateUserRole(ctx interface{}, userId interface{}, role interface{}) *MockUserProvider_UpdateUserRole_Call {
	return &MockUserProvider_UpdateUserRole_Call{Call: _e.mock.On("UpdateUserRole", ctx, userId, role)}
}

func (_c *MockUserProvider_UpdateUserRole_Call) Run(run func(ctx context.Context, userId string, role string)) *MockUserProvider_UpdateUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserProvider_UpdateUserRole_Call) Return(err error) *MockUserProvider_UpdateUserRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserProvider_UpdateUserRole_Call) RunAndReturn(run func(ctx context.Context, userId string, role string) error) *MockUserProvider_UpdateUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGenerator creates a new instance of MockTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGenerator {
	mock := &MockTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenGenerator is an autogenerated mock type for the TokenGenerator type
type MockTokenGenerator struct {
	mock.Mock
}

type MockTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGenerator) EXPECT() *MockTokenGenerator_Expecter {
	return &MockTokenGenerator_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) GenerateAccessToken(userId string, role string) (string, error) {
	ret := _mock.Called(userId, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(userId, role)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(userId, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userId, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenGenerator_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenGenerator_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userId string
//   - role string
func (_e *MockTokenGenerator_Expecter) GenerateAccessToken(userId interface{}, role interface{}) *MockTokenGenerator_GenerateAccessToken_Call {
	return &MockTokenGenerator_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userId, role)}
}

func (_c *MockTokenGenerator_GenerateAccessToken_Call) Run(run func(userId string, role string)) *MockTokenGenerator_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_GenerateAccessToken_Call) Return(s string, err error) *MockTokenGenerator_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenGenerator_GenerateAccessToken_Call) RunAndReturn(run func(userId string, role string) (string, error)) *MockTokenGenerator_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) GenerateRefreshToken(userId string, role string) (string, error) {
	ret := _mock.Called(userId, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(userId, role)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(userId, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userId, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenGenerator_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenGenerator_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - userId string
//   - role string
func (_e *MockTokenGenerator_Expecter) GenerateRefreshToken(userId interface{}, role interface{}) *MockTokenGenerator_GenerateRefreshToken_Call {
	return &MockTokenGenerator_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", userId, role)}
}

func (_c *MockTokenGenerator_GenerateRefreshToken_Call) Run(run func(userId string, role string)) *MockTokenGenerator_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_GenerateRefreshToken_Call) Return(s string, err error) *MockTokenGenerator_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenGenerator_GenerateRefreshToken_Call) RunAndReturn(run func(userId string, role string) (string, error)) *MockTokenGenerator_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTTL provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) GetRefreshTTL() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTTL")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockTokenGenerator_GetRefreshTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTTL'
type MockTokenGenerator_GetRefreshTTL_Call struct {
	*mock.Call
}

// GetRefreshTTL is a helper method to define mock.On call
func (_e *MockTokenGenerator_Expecter) GetRefreshTTL() *MockTokenGenerator_GetRefreshTTL_Call {
	return &MockTokenGenerator_GetRefreshTTL_Call{Call: _e.mock.On("GetRefreshTTL")}
}

func (_c *MockTokenGenerator_GetRefreshTTL_Call) Run(run func()) *MockTokenGenerator_GetRefreshTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenGenerator_GetRefreshTTL_Call) Return(duration time.Duration) *MockTokenGenerator_GetRefreshTTL_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockTokenGenerator_GetRefreshTTL_Call) RunAndReturn(run func() time.Duration) *MockTokenGenerator_GetRefreshTTL_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) ValidateToken(tokenString string) (*jwt.Claims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *jwt.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*jwt.Claims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *jwt.Claims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenGenerator_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockTokenGenerator_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenGenerator_Expecter) ValidateToken(tokenString interface{}) *MockTokenGenerator_ValidateToken_Call {
	return &MockTokenGenerator_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString)}
}

func (_c *MockTokenGenerator_ValidateToken_Call) Run(run func(tokenString string)) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_ValidateToken_Call) Return(claims *jwt.Claims, err error) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockTokenGenerator_ValidateToken_Call) RunAndReturn(run func(tokenString string) (*jwt.Claims, error)) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationSender creates a new instance of MockNotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationSender {
	mock := &MockNotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationSender is an autogenerated mock type for the NotificationSender type
type MockNotificationSender struct {
	mock.Mock
}

type MockNotificationSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationSender) EXPECT() *MockNotificationSender_Expecter {
	return &MockNotificationSender_Expecter{mock: &_m.Mock}
}

// SendPasswordResetNotification provides a mock function for the type MockNotificationSender
func (_mock *MockNotificationSender) SendPasswordResetNotification(ctx context.Context, email string, resetToken string) error {
	ret := _mock.Called(ctx, email, resetToken)

	if len(ret) == 0 {
		panic("no return value specified for SendPasswordResetNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, resetToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationSender_SendPasswordResetNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPasswordResetNotification'
type MockNotificationSender_SendPasswordResetNotification_Call struct {
	*mock.Call
}

// SendPasswordResetNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - resetToken string
func (_e *MockNotificationSender_Expecter) SendPasswordResetNotification(ctx interface{}, email interface{}, resetToken interface{}) *MockNotificationSender_SendPasswordResetNotification_Call {
	return &MockNotificationSender_SendPasswordResetNotification_Call{Call: _e.mock.On("SendPasswordResetNotification", ctx, email, resetToken)}
}

func (_c *MockNotificationSender_SendPasswordResetNotification_Call) Run(run func(ctx context.Context, email string, resetToken string)) *MockNotificationSender_SendPasswordResetNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationSender_SendPasswordResetNotification_Call) Return(err error) *MockNotificationSender_SendPasswordResetNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationSender_SendPasswordResetNotification_Call) RunAndReturn(run func(ctx context.Context, email string, resetToken string) error) *MockNotificationSender_SendPasswordResetNotification_Call {
	_c.Call.Return(run)
	return _c
}
