services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB:-appdb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DOCKER_POSTGRES_USER:-admin} -d ${DOCKER_POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  garage:
    image: dxflrs/garage:v2.2.0
    container_name: garage
    restart: unless-stopped
    ports:
      - "3900:3900"  # S3 API
      - "3901:3901"  # RPC Bind
      - "3902:3902"  # Admin API
    volumes:
      - garage_data:/var/lib/garage/data
      - garage_meta:/var/lib/garage/meta
      - ./config/garage/garage.toml:/etc/garage.toml
    environment:
      GARAGE_CONFIG_FILE: /etc/garage.toml

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:80"    # веб-интерфейс
      - "127.0.0.1:2525:25"    # SMTP
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  postgres_data:
    driver: local
  redis_data:
  garage_data:
  garage_meta:
