env: "local"
reset_token_ttl: 15m
reset_password_base_url: http://localhost/reset-password
grpc:
  port: 44044
  timeout: 10h
jwt:
  access_ttl: 15m
  refresh_ttl: 720h
db:
  max_conns: 10
  min_conns: 2
  max_conn_lifetime: 1h
  max_conn_idle_time: 30m
smtp:
  host: smtp_host
  port: smtp_port
  from: smtp_from