// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"cinema/internal/lib/jwt"
	"cinema/internal/sso/domain"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionStorage creates a new instance of MockSessionStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStorage {
	mock := &MockSessionStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionStorage is an autogenerated mock type for the SessionStorage type
type MockSessionStorage struct {
	mock.Mock
}

type MockSessionStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStorage) EXPECT() *MockSessionStorage_Expecter {
	return &MockSessionStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockSessionStorage
func (_mock *MockSessionStorage) Delete(ctx context.Context, userId string, token string) error {
	ret := _mock.Called(ctx, userId, token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userId, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - token string
func (_e *MockSessionStorage_Expecter) Delete(ctx interface{}, userId interface{}, token interface{}) *MockSessionStorage_Delete_Call {
	return &MockSessionStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, userId, token)}
}

func (_c *MockSessionStorage_Delete_Call) Run(run func(ctx context.Context, userId string, token string)) *MockSessionStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionStorage_Delete_Call) Return(err error) *MockSessionStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, userId string, token string) error) *MockSessionStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function for the type MockSessionStorage
func (_mock *MockSessionStorage) DeleteAll(ctx context.Context, userId string) error {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStorage_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockSessionStorage_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockSessionStorage_Expecter) DeleteAll(ctx interface{}, userId interface{}) *MockSessionStorage_DeleteAll_Call {
	return &MockSessionStorage_DeleteAll_Call{Call: _e.mock.On("DeleteAll", ctx, userId)}
}

func (_c *MockSessionStorage_DeleteAll_Call) Run(run func(ctx context.Context, userId string)) *MockSessionStorage_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionStorage_DeleteAll_Call) Return(err error) *MockSessionStorage_DeleteAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStorage_DeleteAll_Call) RunAndReturn(run func(ctx context.Context, userId string) error) *MockSessionStorage_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockSessionStorage
func (_mock *MockSessionStorage) Exists(ctx context.Context, userId string, token string) (bool, error) {
	ret := _mock.Called(ctx, userId, token)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, userId, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, userId, token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userId, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionStorage_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockSessionStorage_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - token string
func (_e *MockSessionStorage_Expecter) Exists(ctx interface{}, userId interface{}, token interface{}) *MockSessionStorage_Exists_Call {
	return &MockSessionStorage_Exists_Call{Call: _e.mock.On("Exists", ctx, userId, token)}
}

func (_c *MockSessionStorage_Exists_Call) Run(run func(ctx context.Context, userId string, token string)) *MockSessionStorage_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionStorage_Exists_Call) Return(b bool, err error) *MockSessionStorage_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSessionStorage_Exists_Call) RunAndReturn(run func(ctx context.Context, userId string, token string) (bool, error)) *MockSessionStorage_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockSessionStorage
func (_mock *MockSessionStorage) Save(ctx context.Context, userId string, token string, ttl time.Duration) error {
	ret := _mock.Called(ctx, userId, token, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, userId, token, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSessionStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - token string
//   - ttl time.Duration
func (_e *MockSessionStorage_Expecter) Save(ctx interface{}, userId interface{}, token interface{}, ttl interface{}) *MockSessionStorage_Save_Call {
	return &MockSessionStorage_Save_Call{Call: _e.mock.On("Save", ctx, userId, token, ttl)}
}

func (_c *MockSessionStorage_Save_Call) Run(run func(ctx context.Context, userId string, token string, ttl time.Duration)) *MockSessionStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionStorage_Save_Call) Return(err error) *MockSessionStorage_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStorage_Save_Call) RunAndReturn(run func(ctx context.Context, userId string, token string, ttl time.Duration) error) *MockSessionStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserSaver creates a new instance of MockUserSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserSaver {
	mock := &MockUserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserSaver is an autogenerated mock type for the UserSaver type
type MockUserSaver struct {
	mock.Mock
}

type MockUserSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserSaver) EXPECT() *MockUserSaver_Expecter {
	return &MockUserSaver_Expecter{mock: &_m.Mock}
}

// SaveUser provides a mock function for the type MockUserSaver
func (_mock *MockUserSaver) SaveUser(ctx context.Context, email string, passHash []byte) (string, error) {
	ret := _mock.Called(ctx, email, passHash)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return returnFunc(ctx, email, passHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = returnFunc(ctx, email, passHash)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, email, passHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserSaver_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUserSaver_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passHash []byte
func (_e *MockUserSaver_Expecter) SaveUser(ctx interface{}, email interface{}, passHash interface{}) *MockUserSaver_SaveUser_Call {
	return &MockUserSaver_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, email, passHash)}
}

func (_c *MockUserSaver_SaveUser_Call) Run(run func(ctx context.Context, email string, passHash []byte)) *MockUserSaver_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserSaver_SaveUser_Call) Return(id string, err error) *MockUserSaver_SaveUser_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *MockUserSaver_SaveUser_Call) RunAndReturn(run func(ctx context.Context, email string, passHash []byte) (string, error)) *MockUserSaver_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// FindByEmail provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) FindByEmail(ctx context.Context, email string) (domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserProvider_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserProvider_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserProvider_FindByEmail_Call {
	return &MockUserProvider_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserProvider_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserProvider_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_FindByEmail_Call) Return(user domain.User, err error) *MockUserProvider_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (domain.User, error)) *MockUserProvider_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGenerator creates a new instance of MockTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGenerator {
	mock := &MockTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenGenerator is an autogenerated mock type for the TokenGenerator type
type MockTokenGenerator struct {
	mock.Mock
}

type MockTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGenerator) EXPECT() *MockTokenGenerator_Expecter {
	return &MockTokenGenerator_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) GenerateAccessToken(userId string) (string, error) {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(userId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(userId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenGenerator_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenGenerator_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userId string
func (_e *MockTokenGenerator_Expecter) GenerateAccessToken(userId interface{}) *MockTokenGenerator_GenerateAccessToken_Call {
	return &MockTokenGenerator_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userId)}
}

func (_c *MockTokenGenerator_GenerateAccessToken_Call) Run(run func(userId string)) *MockTokenGenerator_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_GenerateAccessToken_Call) Return(s string, err error) *MockTokenGenerator_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenGenerator_GenerateAccessToken_Call) RunAndReturn(run func(userId string) (string, error)) *MockTokenGenerator_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) GenerateRefreshToken(userId string) (string, error) {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(userId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(userId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenGenerator_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenGenerator_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - userId string
func (_e *MockTokenGenerator_Expecter) GenerateRefreshToken(userId interface{}) *MockTokenGenerator_GenerateRefreshToken_Call {
	return &MockTokenGenerator_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", userId)}
}

func (_c *MockTokenGenerator_GenerateRefreshToken_Call) Run(run func(userId string)) *MockTokenGenerator_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_GenerateRefreshToken_Call) Return(s string, err error) *MockTokenGenerator_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenGenerator_GenerateRefreshToken_Call) RunAndReturn(run func(userId string) (string, error)) *MockTokenGenerator_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTTL provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) GetRefreshTTL() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTTL")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockTokenGenerator_GetRefreshTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTTL'
type MockTokenGenerator_GetRefreshTTL_Call struct {
	*mock.Call
}

// GetRefreshTTL is a helper method to define mock.On call
func (_e *MockTokenGenerator_Expecter) GetRefreshTTL() *MockTokenGenerator_GetRefreshTTL_Call {
	return &MockTokenGenerator_GetRefreshTTL_Call{Call: _e.mock.On("GetRefreshTTL")}
}

func (_c *MockTokenGenerator_GetRefreshTTL_Call) Run(run func()) *MockTokenGenerator_GetRefreshTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenGenerator_GetRefreshTTL_Call) Return(duration time.Duration) *MockTokenGenerator_GetRefreshTTL_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockTokenGenerator_GetRefreshTTL_Call) RunAndReturn(run func() time.Duration) *MockTokenGenerator_GetRefreshTTL_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) ValidateToken(tokenString string) (*jwt.Claims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *jwt.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*jwt.Claims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *jwt.Claims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenGenerator_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockTokenGenerator_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenGenerator_Expecter) ValidateToken(tokenString interface{}) *MockTokenGenerator_ValidateToken_Call {
	return &MockTokenGenerator_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString)}
}

func (_c *MockTokenGenerator_ValidateToken_Call) Run(run func(tokenString string)) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_ValidateToken_Call) Return(claims *jwt.Claims, err error) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockTokenGenerator_ValidateToken_Call) RunAndReturn(run func(tokenString string) (*jwt.Claims, error)) *MockTokenGenerator_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
